
default: &default
  adapter: 'postgresql'
  encoding: unicode
  pool: 5
  username: username
  password: password
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: finance_development 

test:
  <<: *default
  database: finance_test

production:
  <<: *default
  database: finance_production
